### ISSUE TITLE
Add a LICENSE file so users can know what terms of use are?

### ISSUE THREAD

**Issue by davidpablocohn** [fiefdx/gauge-chart-js#1]
This looks like an excellent contribution, and I'd love to include it in an open source project I'm working on (https://github.com/davidpablocohn/openrvdas), but there's no LICENSE file to let me know whether it's okay to include. Would be great to either explicitly mark it as public domain or, e.g. MIT License.

Thanks!

**Comment by farukeryilmaz** [comment]
That would actually be great if you publish this repo under **MIT license**. I want to use it in my project but I cannot use it **since it is not licensed**.
Thank you!

**Comment by fiefdx** [comment]
@davidpablocohn @farukeryilmaz  sorry for the long wait, I add the MIT license
